# Task to apply k8s manifests
# as an input you need to provide k8s_app_name as dir name in files/manifests directory

- name: Delete directory
  file:
    path: "/tmp/{{k8s_app_name}}"
    state: absent

- name: Create directory
  file:
    path: "/tmp/{{k8s_app_name}}"
    state: directory
    mode: 0777

- name: Copy templates
  template:
    src: "{{item}}"
    dest: "/tmp/{{k8s_app_name}}"
  with_fileglob:
    - "{{playbook_dir}}/files/manifests/{{k8s_app_name}}/*.yaml"

- name: Apply manifests 
  shell: "kubectl apply -f /tmp/{{k8s_app_name}}"
  environment:
    KUBECONFIG: "{{kubeconfig_path}}"

