- hosts: k8s-cluster
  gather_facts: no
  environment:
    LIBVIRT_DEFAULT_URI: "qemu:///system"
  tasks:
    - name: Set localkubeconfig path
      set_fact:
        local_kubeconfig: "{{playbook_dir}}/kubeconfig-{{cluster_name}}"

    - name: Install Cilium CNI
      include_role:
        name: k8s-setup
        tasks_from: k8s-cni-{{k8s_cni}}.yaml
    