
- name: Debug message
  debug: 
    msg: "Creating new VM for k8s lab"

- name: Debug message
  debug: 
    msg: "Downloading VM image from {{ vm_image_url }} as {{ k8s_vm_path }}"
  when: vm_image_url is defined
  run_once: yes      

- name: "Download VM image"
  get_url:
    url: "{{ vm_image_url }}"
    dest: "{{ k8s_vm_path }}"
  become: yes
  delegate_to: localhost
  when: vm_image_url is defined
  run_once: yes

- name: "Copy VM image from local path {{ vm_image_path }} as {{ k8s_vm_path }}"
  copy:
    src: "{{ vm_image_path }}"
    dest: "{{ k8s_vm_path }}"
    remote_src: true
  become: yes
  delegate_to: localhost
  when: vm_image_path is defined
  run_once: yes

- name: "Update disk size for vm {{ k8s_vm_name }}"
  command: "qemu-img resize {{k8s_vm_path}} {{k8s_vm_disk_size}}"
  become: yes
  delegate_to: localhost
  run_once: yes  

- name: Set path to SSH key
  set_fact: 
    k8s_vm_user_ssh_key_path: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"

- name: Generate args to add required Kernel params
  set_fact:
    args_to_add_kernel_params: "{{ args_to_add_kernel_params | default() }} --append-line '{{vm_boot_config_file}}:{{ item }}'"
  loop:
    - CONFIG_BPF=y
    - CONFIG_BPF_SYSCALL=y
    - CONFIG_NET_CLS_BPF=y
    - CONFIG_BPF_JIT=y
    - CONFIG_NET_CLS_ACT=y
    - CONFIG_NET_SCH_INGRESS=y
    - CONFIG_CRYPTO_SHA1=y
    - CONFIG_CRYPTO_USER_API_HASH=y
    - CONFIG_CGROUPS=y
    - CONFIG_CGROUP_BPF=y
    - CONFIG_PERF_EVENTS=y
    - CONFIG_SCHEDSTATS=y  
# --- old    
    # - CONFIG_NET_CLS_BPF=y
    # - CONFIG_BPF_JIT=y
    # - CONFIG_NET_CLS_ACT=y
    # - CONFIG_NET_SCH_INGRESS=y
    # - CONFIG_CRYPTO_USER_API_HASH=y



#- name: Generate args to add required Kernel params
#  set_fact:
#    #args_to_add_kernel_params: "--append-line '/boot/config-5.15.0-1032-kvm:test=y'"
#    args_to_add_kernel_params: "--append-line '/boot/config-5.15.0-1032-kvm:test=y'"

- name: Add SSH key to the VM
  command: "virt-sysprep -a {{k8s_vm_path}} --ssh-inject root:file:{{ k8s_vm_user_ssh_key_path }} --run-command 'ssh-keygen -A'  --copy-in {{role_path}}/files/10-dhcp.network:/etc/systemd/network/ {{args_to_add_kernel_params}}" # --selinux-relabel"
  become: yes
  delegate_to: localhost
  run_once: yes

- name: Create the VM
  command:  | 
    virt-install \
    --memory {{ k8s_vm_memory }} \
    --vcpus {{ k8s_vm_cpu }} \
    --name {{ k8s_vm_name }} \
    --disk {{k8s_vm_path}} \
    --os-variant centos7.0 \
    --virt-type kvm \
    --graphics none \
    --network network={{k8s_vm_network}} \
    --import
  become: yes
  delegate_to: localhost
  run_once: yes    

#    --os-type Linux \  