apiVersion: v1
kind: Service
metadata:
  name: shared-service
  annotations:
    service.cilium.io/global: "true"
  namespace: shared-service      
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80